export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_COLLECTION_INIT = 'FETCH_COLLECTION_INIT';
export const FETCH_COLLECTION_REQUEST = 'FETCH_COLLECTION_REQUEST';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE';

export const FETCH_COLLECTIONS_REQUEST = 'FETCH_COLLECTIONS_REQUEST';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';

export const SET_DAILY_LOG = 'SET_DAILY_LOG';
export const SET_MONTHLY_LOG = 'SET_MONTHLY_LOG';
export const SET_FUTURE_LOG = 'SET_FUTURE_LOG';

export const CREATE_BULLET_REQUEST = 'CREATE_BULLET_REQUEST';
export const CREATE_BULLET_SUCCESS = 'CREATE_BULLET_SUCCESS';
export const CREATE_BULLET_FAILURE = 'CREATE_BULLET_FAILURE';

export const UPDATE_BULLET_REQUEST = 'UPDATE_BULLET_REQUEST';
export const UPDATE_BULLET_SUCCESS = 'UPDATE_BULLET_SUCCESS';
export const UPDATE_BULLET_FAILURE = 'UPDATE_BULLET_FAILURE';

export const DELETE_BULLET_REQUEST = 'DELETE_BULLET_REQUEST';
export const DELETE_BULLET_SUCCESS = 'DELETE_BULLET_SUCCESS';
export const DELETE_BULLET_FAILURE = 'DELETE_BULLET_FAILURE';

export const FETCH_BULLET_REQUEST = 'FETCH_BULLET_REQUEST';
export const FETCH_BULLET_SUCCESS = 'FETCH_BULLET_SUCCESS';
export const FETCH_BULLET_FAILURE = 'FETCH_BULLET_FAILURE';

export const COMPLETE_TASK_REQUEST = 'COMPLETE_TASK_REQUEST';
export const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';

export const MIGRATE_TASK_REQUEST = 'MIGRATE_TASK_REQUEST';
export const MIGRATE_TASK_SUCCESS = 'MIGRATE_TASK_SUCCESS';
export const MIGRATE_TASK_FAILURE = 'MIGRATE_TASK_FAILURE';

export const SCHEDULE_TASK_REQUEST = 'SCHEDULE_TASK_REQUEST';
export const SCHEDULE_TASK_SUCCESS = 'SCHEDULE_TASK_SUCCESS';
export const SCHEDULE_TASK_FAILURE = 'SCHEDULE_TASK_FAILURE';

export const DISCARD_TASK_REQUEST = 'DISCARD_TASK_REQUEST';
export const DISCARD_TASK_SUCCESS = 'DISCARD_TASK_SUCCESS';
export const DISCARD_TASK_FAILURE = 'DISCARD_TASK_FAILURE';

export const RESET_TASK_REQUEST = 'RESET_TASK_REQUEST';
export const RESET_TASK_SUCCESS = 'RESET_TASK_SUCCESS';
export const RESET_TASK_FAILURE = 'RESET_TASK_FAILURE';
